name: credit_risk
channels:
  - defaults
dependencies:
- python
- jupyter
# data manipulation
- numpy
- pandas
# data visualization
- matplotlib
- seaborn
- plotly
# statistical models
- scipy
- statsmodels 
# model building
- scikit-learn
- xgboost 
- tensorflow 